# Generated by Django 4.1.2 on 2022-10-15 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_store_id_review_user_id_alter_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='local',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 15, 17, 59, 11, 596186)),
        ),
    ]
