# Generated by Django 4.1.2 on 2022-10-15 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 15, 23, 4, 36, 98065), null=True),
        ),
    ]
