# Generated by Django 4.1.2 on 2022-10-18 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 10, 16, 52, 723432), null=True),
        ),
    ]
