# Generated by Django 4.1.2 on 2022-10-22 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 18, 2, 33, 305927), null=True),
        ),
    ]
