<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-12 12:12
=======
# Generated by Django 4.1.2 on 2022-10-12 02:11
>>>>>>> 575f1dc7a87a85467f8250814910fb03a24fe396

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
