# Generated by Django 4.1.2 on 2022-10-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
