# Generated by Django 4.1.2 on 2022-10-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
