# Generated by Django 3.2.15 on 2022-10-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.category'),
        ),
    ]
