# Generated by Django 4.1.2 on 2022-10-20 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='like_count',
        ),
        migrations.AddField(
            model_name='store',
            name='like_users',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
